import Head from 'next/head'
import { Inter } from 'next/font/google'
// import Feature from '@/components/home/Feature'
import HomeAbout from '@/components/home/HomeAbout'
import OurServices from '@/components/home/OurServices'
import ClientsTestimonials from '@/components/home/ClientsTestimonials'
import WhyChooseUs from '@/components/home/WhyChooseUs'
import WorkWithUs from '@/components/home/WorkWithUs'
import MiniSlider from '@/components/home/MiniSlider'
import GetInTouch from '@/components/home/GetInTouch'
import Banner from '@/components/header/Banner'
import dynamic from 'next/dynamic'
const inter = Inter({ subsets: ['latin'] })
const Feature = dynamic(() => import('@/components/home/Feature'))
export default function Home() {

  return (
    <>
     
      <Head>
        <title>Lxecon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
     <Feature/>
      <HomeAbout />
      <OurServices />
      <ClientsTestimonials />
      <WhyChooseUs />
      <MiniSlider />
      <WorkWithUs />
      <GetInTouch />
    </>
  )
}
