import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Feature from '@/components/home/Feature'
import HomeAbout from '@/components/home/HomeAbout'
import OurServices from '@/components/home/OurServices'
import OurCompleteCrafts from '@/components/home/OurCompleteCrafts'
import ClientsTestimonials from '@/components/home/ClientsTestimonials'
import WhyChooseUs from '@/components/home/WhyChooseUs'
import WorkWithUs from '@/components/home/WorkWithUs'
import MiniSlider from '@/components/home/MiniSlider'
import LatestBlogs from '@/components/home/LatestBlogs'
import GetInTouch from '@/components/home/GetInTouch'
import OurProgress from '@/components/home/OurProgress'
import Banner from '@/components/header/Banner'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Lxecon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner/>
      <Feature />
      <HomeAbout/>
      <OurServices/>
      {/* <OurCompleteCrafts/> */}
      <ClientsTestimonials/>
      <WhyChooseUs/>
      <MiniSlider/>
      <WorkWithUs/>
      {/* <OurProgress/> */}
      <LatestBlogs/>

      <GetInTouch/>
      



    </>
  )
}
